...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -368,9 +368,7 @@ ___x_cmd_main(){
                         return 1
                     fi
                     rm -rf "$___X_CMD_ROOT" ;;
-        reinstall)  xrc clear
-                    RELOAD=1 xrc upgrade
-                    ;;
+        reinstall)  xrc clear && RELOAD=1 xrc upgrade ;;
 
         z)                                      (   xrc zuz && zuz z "$@"   ) ;;
         uz)                                     (   xrc zuz && zuz uz "$@"  ) ;;
@@ -389,21 +387,20 @@ ___x_cmd_main(){
         javascript|js|node)                     ___x_cmd_node "$@" ;;
         npm)                                    ___x_cmd_npm "$@" ;;
         npx)                                    ___x_cmd_npx "$@" ;;
-        ts)
-            local arg
-            local argstr
-            while [ $# -ge 0 ]; do
-                case "$arg" in
-                    -*)     argstr="$argstr $arg"   ;;
-                    *)      break
-                esac
-            done
-            local script
-            # script="$(___x_cmd_official_which "$1")"
-            script="$1"
-            shift
-            x npx @typeshell/exec "$argstr" "$script" "$@"
-            ;;
+        ts)         local arg
+                    local argstr
+                    while [ $# -ge 0 ]; do
+                        case "$arg" in
+                            -*)     argstr="$argstr $arg"   ;;
+                            *)      break
+                        esac
+                    done
+                    local script
+                    # script="$(___x_cmd_official_which "$1")"
+                    script="$1"
+                    shift
+                    x npx @typeshell/exec "$argstr" "$script" "$@"
+                    ;;
         ruby|rb)                                ruby "$(___x_cmd_official_which "$2")" "$@"      ;;
         lua)            ;;
 
@@ -419,26 +416,23 @@ ___x_cmd_main(){
 
         run)                                    ___x_cmd_run_by_file "$@"            ;;
         search_path)                            ___x_cmd_search_path "$@"            ;;
-        which|w)
-            local p
-            for p in "$@"; do
-                if ! p=$(___x_cmd_which_one "$p"); then
-                    printf "%s\n" "Fail to find path for $p" >&2
-                    return
-                else
-                    printf "%s\n" "$p"
-                fi
-            done
-            ;;
-        _x_cmd_advise_json)     ___x_cmd_x_cmd_advise_json "$@" ;;
-        *)
-            local p
-            if p="$(___x_cmd_which_one "$subcmd" 2>/dev/null)"; then
-                ___x_cmd_run_by_file "$p" "$@" 2>/dev/null
-                return
-            fi
-
-            printf "%s" "$p"
+        which|w)    local p
+                    for p in "$@"; do
+                        if ! p=$(___x_cmd_which_one "$p"); then
+                            printf "%s\n" "Fail to find path for $p" >&2
+                            return
+                        else
+                            printf "%s\n" "$p"
+                        fi
+                    done
+                    ;;
+        _x_cmd_advise_json)                     ___x_cmd_x_cmd_advise_json "$@" ;;
+        *)          local p
+                    if p="$(___x_cmd_which_one "$subcmd" 2>/dev/null)"; then
+                        ___x_cmd_run_by_file "$p" "$@" 2>/dev/null
+                        return
+                    fi
+                    printf "%s" "$p"
     esac
 }
 
