...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -374,13 +374,13 @@ ___x_cmd_main(){
 
         log)                                    xrc x-cmd/_v0/log && ___x_cmd_log "$@" ;;
 
-        upgrade)    eval "$(curl https://get.x-cmd.com/all)" ;;
-        clear)      if ! grep "___x_cmd_http_get()" "$___X_CMD_ROOT/xrc/latest" >/dev/null 2>&1; then
-                        ___xrc_log debug "'$___X_CMD_ROOT/xrc/latest' NOT found. Please manually clear cache folder: $___X_CMD_ROOT"
-                        return 1
-                    fi
-                    rm -rf "$___X_CMD_ROOT" ;;
-        reinstall)  x clear && RELOAD=1 x upgrade ;;
+        upgrade)                                eval "$(curl https://get.x-cmd.com/all)" ;;
+        clear)                                  if ! grep "___x_cmd_http_get()" "$___X_CMD_ROOT/xrc/latest" >/dev/null 2>&1; then
+                                                    ___xrc_log debug "'$___X_CMD_ROOT/xrc/latest' NOT found. Please manually clear cache folder: $___X_CMD_ROOT"
+                                                    return 1
+                                                fi
+                                                rm -rf "$___X_CMD_ROOT" ;;
+        reinstall)                              x clear && RELOAD=1 x upgrade ;;
 
         z)                                      (   xrc zuz && zuz z "$@"   ) ;;
         uz)                                     (   xrc zuz && zuz uz "$@"  ) ;;
@@ -428,36 +428,36 @@ ___x_cmd_main(){
 
         run)                                    ___x_cmd_run_by_file "$@"            ;;
         search_path)                            ___x_cmd_search_path "$@"            ;;
-        which|w)    local p
-                    for p in "$@"; do
-                        if ! p=$(___x_cmd_which_one "$p"); then
-                            printf "%s\n" "Fail to find path for $p" >&2
-                            return
-                        else
-                            printf "%s\n" "$p"
-                        fi
-                    done
-                    ;;
+        which|w)                                local p
+                                                for p in "$@"; do
+                                                    if ! p=$(___x_cmd_which_one "$p"); then
+                                                        printf "%s\n" "Fail to find path for $p" >&2
+                                                        return
+                                                    else
+                                                        printf "%s\n" "$p"
+                                                    fi
+                                                done
+                                                ;;
         _x_cmd_advise_json)                     ___x_cmd_x_cmd_advise_json "$@" ;;
         wsroot)                                 ___x_cmd_workspace_root "$@" ;;
         *)
-                    local p
-                    if p="$(___x_cmd_which_one "$subcmd")"; then
-                        if [ "${p#$___X_CMD_ROOT}" = "$p" ]; then
-                            # workspace
-                            ___X_CMD_WSROOT="$filepath"
-                            ___X_CMD_WSROOT="$(dirname "$___X_CMD_WSROOT")"
-                            ___X_CMD_WSROOT="$(cd "$___X_CMD_WSROOT" && pwd)/"
-                            ___X_CMD_WSROOT="${___X_CMD_WSROOT%/.x-cmd/*}"
-                            export ___X_CMD_WSROOT
-                        fi
-                        export ___X_CMD_ROOT
-                        ___x_cmd_run_by_file "$p" "$@" # 2>/dev/null
-                        return
-                    else
-                        printf "%s" "Error" >&2
-                    fi
-                    printf "%s" "$p"
+                                                local p
+                                                if p="$(___x_cmd_which_one "$subcmd")"; then
+                                                    if [ "${p#$___X_CMD_ROOT}" = "$p" ]; then
+                                                        # workspace
+                                                        ___X_CMD_WSROOT="$filepath"
+                                                        ___X_CMD_WSROOT="$(dirname "$___X_CMD_WSROOT")"
+                                                        ___X_CMD_WSROOT="$(cd "$___X_CMD_WSROOT" && pwd)/"
+                                                        ___X_CMD_WSROOT="${___X_CMD_WSROOT%/.x-cmd/*}"
+                                                        export ___X_CMD_WSROOT
+                                                    fi
+                                                    export ___X_CMD_ROOT
+                                                    ___x_cmd_run_by_file "$p" "$@" # 2>/dev/null
+                                                    return
+                                                else
+                                                    printf "%s" "Error" >&2
+                                                fi
+                                                printf "%s" "$p"
     esac
 }
 
