...

diff --git a/lib/test b/lib/test
--- a/lib/test
+++ b/lib/test
@@ -8,24 +8,6 @@ ___x_cmd_test(){
     ___x_cmd_test_cycle_run "$@"
 }
 
-___x_cmd_test_cycle_init(){
-    xrc:mod assert/latest
-    assert(){
-        ___x_cmd_assert "$@"
-    }
-
-    assert_true_for_all_func() {
-        < "${1:-$___X_CMD_TEST_CURRENT_TESTCASE}" \
-            awk -v PREFIX="${2:-test}" '$0~ "^" PREFIX "_[^\(]+\(\)"{ gsub(/\(\)\{/, "", $0); print $0 }' | \
-        while read -r ___line; do
-            printf "%s\n" "Testing Function: $___line"
-            if ! eval "$___line"; then
-                printf "%s" "\033[0;31m======= Fail at function: %s \033[0m" "$___line" >&2
-                break
-            fi
-        done
-    }
-}
 
 ___x_cmd_test_cycle_run(){
     local target="${1}"
@@ -50,6 +32,28 @@ ___x_cmd_test_cycle_run(){
     return "$code"
 }
 
+# Section: init
+___x_cmd_test_cycle_init(){
+    xrc:mod assert/latest
+    assert(){
+        ___x_cmd_assert "$@"
+    }
+
+    assert_true_for_all_func() {
+        < "${1:-$___X_CMD_TEST_CURRENT_TESTCASE}" \
+            awk -v PREFIX="${2:-test}" '$0~ "^" PREFIX "_[^\(]+\(\)"{ gsub(/\(\)\{/, "", $0); print $0 }' | \
+        while read -r ___line; do
+            printf "%s\n" "Testing Function: $___line"
+            if ! eval "$___line"; then
+                printf "%s" "\033[0;31m======= Fail at function: %s \033[0m" "$___line" >&2
+                break
+            fi
+        done
+    }
+}
+# EndSection
+
+# Section: cycle run
 ___x_cmd_test_cycle_run_folder(){
 
     local testcase
@@ -114,3 +118,4 @@ ___x_cmd_test___cycle_run_folder_exec() {
         :
     fi
 }
+# EndSection
