...

diff --git a/lib/test b/lib/test
--- a/lib/test
+++ b/lib/test
@@ -41,6 +41,18 @@ ___x_cmd_test_cycle_exec(){
     return "$code"
 }
 
+___x_cmd_test_assert_true_for_all_func() {
+    < "${1:-$___X_CMD_TEST_CURRENT_TESTCASE}" \
+        awk -v PREFIX="${2:-test}" '$0~ "^" PREFIX "_[^\\(]+\\(\\)"{ gsub(/\(\)\{/, "", $0); print $0 }' | \
+    while read -r ___line; do
+        printf "%s\n" "Testing Function: $___line"
+        if ! eval "$___line"; then
+            printf "\033[0;31m======= Fail at function: %s \033[0m" "$___line" >&2
+            return 1
+        fi
+    done
+}
+
 ___x_cmd_test_true_or_exit(){
     local code
     "$@"
@@ -64,19 +76,7 @@ ___x_cmd_test_cycle_init(){
 
     alias @assert='___x_cmd_test_true_or_exit ___x_cmd_assert'
 
-    ___x_cmd_assert_true_for_all_func() {
-        < "${1:-$___X_CMD_TEST_CURRENT_TESTCASE}" \
-            awk -v PREFIX="${2:-test}" '$0~ "^" PREFIX "_[^\\(]+\\(\\)"{ gsub(/\(\)\{/, "", $0); print $0 }' | \
-        while read -r ___line; do
-            printf "%s\n" "Testing Function: $___line"
-            if ! eval "$___line"; then
-                printf "\033[0;31m======= Fail at function: %s \033[0m" "$___line" >&2
-                return 1
-            fi
-        done
-    }
-
-    alias @assert:file:func='___x_cmd_test_true_or_exit ___x_cmd_assert_true_for_all_func'
+    alias @assert:file:func='___x_cmd_test_true_or_exit ___x_cmd_test_assert_true_for_all_func'
 }
 # EndSection
 
