...

diff --git a/lib/test b/lib/test
--- a/lib/test
+++ b/lib/test
@@ -8,6 +8,26 @@ ___x_cmd_test(){
     ___x_cmd_test_main "$@"
 }
 
+___x_cmd_test_init(){
+    xrc:mod assert/latest
+    assert(){
+        ___x_cmd_assert "$@"
+    }
+
+    assert_true_for_all_func() {
+        < "${1:-$___X_CMD_TEST_CURRENT_TESTCASE}" \
+            awk -v PREFIX="${2:-test}" '$0~ "^" PREFIX "_[^\(]+\(\)"{ gsub(/\(\)\{/, "", $0); print $0 }' | \
+        while read -r ___line; do
+            printf "%s\n" "Testing Function: $___line"
+            if ! eval "$___line"; then
+                printf "%s" "\033[0;31m======= Fail at function: %s \033[0m" "$___line" >&2
+                break
+            fi
+        done
+    }
+
+}
+
 ___x_cmd_test_main(){
     local target="${1}"
     if [ -z "$target" ]; then
@@ -21,6 +41,7 @@ ___x_cmd_test_main(){
     # printf "%s\n" "-------------------"
     ___x_cmd_ui_sep "━"
     (
+        ___x_cmd_test_init
         cd "$target" && NAME="" INDENT="" ___x_cmd_test_folder "$(pwd)"
     )
     local code="$?"
