...

diff --git a/lib/tmpl b/lib/tmpl
--- a/lib/tmpl
+++ b/lib/tmpl
@@ -1,7 +1,7 @@
 
 
-___X_CMD_TMPL_B="${___X_CMD_UNSEENCHAR_001}"
-___X_CMD_TMPL_E="${___X_CMD_UNSEENCHAR_002}"
+___X_CMD_TMPL_B='=' # "${___X_CMD_UNSEENCHAR_001}"
+___X_CMD_TMPL_E='/' # "${___X_CMD_UNSEENCHAR_002}"
 
 ___X_CMD_T="${___X_CMD_TMPL_B}"
 
@@ -16,10 +16,6 @@ ___X_CMD_T7="${___X_CMD_TMPL_B}7${___X_CMD_TMPL_E}"
 ___X_CMD_T8="${___X_CMD_TMPL_B}8${___X_CMD_TMPL_E}"
 ___X_CMD_T9="${___X_CMD_TMPL_B}9${___X_CMD_TMPL_E}"
 
-
-# x tmpl "${___X_CMD_TX}, ${___X_CMD_TX}" hello world
-x tmpl "${___X_CMD_T}:abc:, ${___X_CMD_TX}:cde:" :cde:=hello :abc:=world
-# x tmpl "${___X_CMD_T}:abc:, ${___X_CMD_TX}:cde:" :cde:  hello
 
 ___x_cmd_tmpl(){
     local ___X_CMD_TMPL_
@@ -63,12 +59,11 @@ ___x_cmd_tmpl_sub_eq_(){
 ___x_cmd_tmpl_1by1_(){
     ___X_CMD_TMPL_=
 
-    local str="$1"; shift
-    local ___X_CMD_STR_REPLACE_="$str"
+    local ___X_CMD_STR_REPLACE_="$___X_CMD_TMPL_TEMPLATE"
     local arg; for arg in "$@"; do
-        if ___x_cmd_str_replace_ "$___X_CMD_STR_REPLACE_" "${___X_CMD_TX}" "$arg"; then
+        if ! ___x_cmd_str_replace_ "$___X_CMD_STR_REPLACE_" "${___X_CMD_TX}" "$arg"; then
             ___X_CMD_TMPL_="$___X_CMD_STR_REPLACE_"
-            x:error "Fail to proceed in: $arg"
+            x:error "x tmpl: Fail to proceed in [$arg]"
             return 1
         fi
     done
@@ -87,9 +82,9 @@ ___x_cmd_str_replace_(){
     local src="${2:?Source substring}"
     local tgt="${3:?Target string}"
 
-    local rest=${org#*${src}}
+    local rest=${org#*"${src}"}
     [ "$rest" != "$org" ] || { ___X_CMD_STR_REPLACE_="$org"; return 1; }
-    ___X_CMD_STR_REPLACE_="${rest}${tgt}${org%%${src}*}"
+    ___X_CMD_STR_REPLACE_="${org%%"${src}"*}${tgt}${rest}"
 }
 
 # Not used
@@ -102,3 +97,13 @@ ___x_cmd_tmpl_name(){
     ___x_cmd_tmpl_name_ "$@"
     printf "%s\n" "$___X_CMD_TMPL_NAME_"
 }
+
+
+x tmpl "${___X_CMD_TX}, ${___X_CMD_TX}" hello world
+x tmpl "${___X_CMD_T}:abc:, ${___X_CMD_T}:cde:" :cde:=world :abc:=hello
+
+___X_CMD_TMPL_="${___X_CMD_T}:abc:, ${___X_CMD_T}:cde:"
+x tmpl_ "$___X_CMD_TMPL_" :cde:  world
+x tmpl_ "$___X_CMD_TMPL_" :abc:  hello
+printf "%s\n" "$___X_CMD_TMPL_"
+
