...

diff --git a/_v0/boot b/_v0/boot
--- a/_v0/boot
+++ b/_v0/boot
@@ -3,9 +3,13 @@
 # Section: initrc, consider external module.
 ___x_cmd_boot(){
     local subcmd="$1"
+    if ! mkdir -p "$HOME/.x-cmd/.boot"; then
+        printf "boot abort for mkdir fails: %s\n" "$HOME/.x-cmd/.boot" >/dev/stderr
+        return 1
+    fi
+
     case "$subcmd" in
         setup)
-            mkdir -p "$HOME/.x-cmd/.boot"
             cat > "$HOME/.x-cmd/.boot/boot" <<A
 # Do NOT modify manually for this file is auto generated by command: x boot setup
 
